"""RPC protocol implementation for NotebookLM batchexecute API."""

from .types import (
    RPCMethod,
    BATCHEXECUTE_URL,
    QUERY_URL,
    UPLOAD_URL,
    StudioContentType,
    ArtifactStatus,
    AudioFormat,
    AudioLength,
    VideoFormat,
    VideoStyle,
    QuizQuantity,
    QuizDifficulty,
    InfographicOrientation,
    InfographicDetail,
    SlideDeckFormat,
    SlideDeckLength,
    ReportFormat,
    ChatGoal,
    ChatResponseLength,
    DriveMimeType,
    ExportType,
)
from .encoder import encode_rpc_request, build_request_body
from .decoder import (
    strip_anti_xssi,
    parse_chunked_response,
    extract_rpc_result,
    collect_rpc_ids,
    decode_response,
    RPCError,
)

__all__ = [
    "RPCMethod",
    "BATCHEXECUTE_URL",
    "QUERY_URL",
    "UPLOAD_URL",
    "StudioContentType",
    "ArtifactStatus",
    "AudioFormat",
    "AudioLength",
    "VideoFormat",
    "VideoStyle",
    "QuizQuantity",
    "QuizDifficulty",
    "InfographicOrientation",
    "InfographicDetail",
    "SlideDeckFormat",
    "SlideDeckLength",
    "ReportFormat",
    "ChatGoal",
    "ChatResponseLength",
    "DriveMimeType",
    "ExportType",
    "encode_rpc_request",
    "build_request_body",
    "strip_anti_xssi",
    "parse_chunked_response",
    "extract_rpc_result",
    "collect_rpc_ids",
    "decode_response",
    "RPCError",
]
